

const CHANGE_HOME_NAVS = 'CHANGE_HOME_NAVS'
const CHANGE_HOME_BANNERS = 'CHANGE_HOME_BANNERS'
const CHANGE_HOME_SPECIALS = 'CHANGE_HOME_SPECIALS'

export { CHANGE_HOME_NAVS , CHANGE_HOME_BANNERS, CHANGE_HOME_SPECIALS }